services:
  - type: web
    name: google-ads-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn google_scraper:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_HOST
        fromService:
          type: redis
          name: scraper-cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: scraper-cache
          property: port

  - type: redis
    name: scraper-cache
    ipAllowList: []
    plan: free
