services:
  - type: web
    name: google-ads-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn google_scraper:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
